version: '3.8'

services:
  frontend:
    build:
      context: ./aura_frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./aura_frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
    networks:
      - aura

  backend:
    build:
      context: ./aura_backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./aura_backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./aura_backend/.env
    networks:
      - aura

networks:
  aura:
    driver: bridge