version: '3.8'

services:
  frontend:
    build:
      context: ./aura_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - aura

  backend:
    build:
      context: ./aura_backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static/
    env_file:
      - ./aura_backend/.env
    networks:
      - aura

networks:
  aura:
    driver: bridge

volumes:
  static_volume:
