version: '3.8'

services:
  frontend:
    build:
      context: ./aura_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./aura_frontend:/app
      - /app/node_modules
    command: npm run dev -- --host