version: '3.8'

services:
  frontend:
<<<<<<< HEAD
    image: prateek2004/insurance-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - aura
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: prateek2004/insurance-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=z%9oq2r3)j+5+7#b8kpr9et*f%o!n&2br7!=35ox4%+-pvk9s1
      - DEBUG=True
      - ALLOWED_HOSTS=*
    volumes:
      - db_data:/app/db
    networks:
      - aura
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  aura:
    driver: bridge
=======
    build:
      context: ./aura_frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./aura_frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
    networks:
      - aura

  backend:
    build:
      context: ./aura_backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./aura_backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./aura_backend/.env
    networks:
      - aura

networks:
  aura:
    driver: bridge
>>>>>>> 0e5f8308c3ac3ad34b2c4fca7ada2de16b56b36d
